#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require './higly_expression'

class OpClass
  def initialize(name, assoc, operators)
    @name = name
    @assoc = assoc
    @operators = operators
    @prename = nil
    @parent = nil
  end

  attr_reader :assoc
  attr_accessor :name, :prename, :operators, :parent
end

class Op
  def initialize(kind, op_list)
    @kind = kind
    @op_list = op_list
  end

  attr_reader :kind, :op_list
end

class HiglyParser < Racc::Parser

module_eval(<<'...end higly_racc.y/module_eval...', 'higly_racc.y', 134)
attr_reader :opclasses, :operators, :tree_flag, :nonterms

def parse(f)
  @q = []
  @lineno = 1
  @termno = 1
  @opclasses = Hash.new
  @operators = Hash.new
  @nonterms = Hash.new
  @default_assoc = :left
  @tree_flag = false

  f.each do |line|
    line.strip!
    until line.empty?
      case line
      when /\A<expression>/
        @q << [:EXP, $&]
      when /\Aleft/
        @q << [:LEFT, $&]
      when /\Atree/
        @q << [:TREE, $&]
      when /\A%action/
        @q << [:ACTION, $&]
      when /\A%assoc/
        @q << [:ASSOC, $&]
      when /\A%operator/
        @q << [:OPERATOR, $&]
      when /\Aright/
        @q << [:RIGHT, $&]
      when /\Anonassoc/
        @q << [:NONASSOC, $&]
      when /\A-action/
        @q << [:ACHECK, $&]
      when /\A%\+/
        @q << [:PPLUS, $&]
      when /\A_/
        @q << ['_', $&]
      when /\A@/
        @q << [:OP, $&]
      when /\A(0|[1-9]\d*)\.\d+/
        @q << [:NUM, $&]
      when /\A(0|[1-9])\d*/
        @q << [:NUM, $&]
      when /\A'([[^']&&\S]*)'/
        @q << [:S_LITERAL, $1]
      when /\A\(/
        @q << ['(', $&]
      when /\A\)/
        @q << [')', $&]
      when /\A\./
        @q << ['.', $&]
      when /\A,/
        @q << [',', $&]
      when /\A;/
        @q << [';', $&]
      when /\A:/
        @q << [':', $&]
      when /\A=/
        @q << ['=', $&]
      when /\A\|/
        @q << ['|', $&]
      when /\A[a-zA-Z_]\w*/
        @q << [:IDENTIFIER, $&]
      when /\A./
      end
      line = $'
    end
    @q << [:EOL, '']
  end
  @q << [false, '$']
  do_parse
  puts "parse is successfull."
end

def next_token
  l = @q.shift
  while l[0] == :EOL do
    @lineno += 1
    l = @q.shift
  end
  return l
end

def on_error(t, v, values)
  raise Racc::ParseError, "line #{@lineno}: syntax error on #{v.inspect}."
end

def token_register(t)
  if @nonterms.key?(t)
    return t
  elsif @operators.key?(t)
    return @operators[t]
  else
    if t =~ /\A\w+/ then
      token = t.upcase
    elsif t.size == 1 then
      token = "\'#{t}\'"
    else
      token = "OP#{@termno}"
      @operators.key?(t) ? nil : @termno += 1
    end
    @operators[t] = token
    return token
  end
end

...end higly_racc.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    40,    40,    40,    40,    40,    39,    39,    39,    39,    39,
    39,    39,    38,    38,    38,    38,    38,    38,    38,    39,
     8,     2,     3,     9,    10,     8,    38,     8,     9,    10,
     9,    10,     8,    11,    14,     9,    10,    22,    23,    45,
    24,    57,    46,    63,    46,    65,    46,    18,    46,    28,
    29,    30,    28,    29,    30,    43,    19,    44,    28,    29,
    30,    20,    14,    26,    32,    33,    42,    40,    40,    50,
    32,    56,    58,    40,    61 ]

racc_action_check = [
    23,    43,    46,    56,    61,    23,    43,    46,    56,    61,
    36,    48,    23,    43,    46,    56,    61,    36,    48,    59,
     2,     0,     1,     2,     2,     5,    59,     6,     5,     5,
     6,     6,     7,     3,     4,     7,     7,    14,    14,    34,
    14,    52,    34,    60,    52,    64,    60,     8,    64,    19,
    19,    19,    24,    24,    24,    33,     9,    33,    44,    44,
    44,    10,    12,    18,    20,    22,    32,    37,    40,    41,
    42,    50,    53,    55,    58 ]

racc_action_pointer = [
    19,    22,    17,    33,    21,    22,    24,    29,    43,    52,
    57,   nil,    49,   nil,    23,   nil,   nil,   nil,    58,    39,
    56,   nil,    52,    -8,    42,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    57,    40,    23,   nil,    -3,    59,   nil,   nil,
    60,    51,    62,    -7,    48,   nil,    -6,   nil,    -2,   nil,
    56,   nil,    25,    54,   nil,    65,    -5,   nil,    59,     6,
    27,    -4,   nil,   nil,    29,   nil ]

racc_action_default = [
   -33,   -33,    -2,   -33,   -33,    -2,    -2,    -2,   -33,   -33,
   -33,    66,    -1,   -16,   -33,    -3,    -4,    -5,   -33,   -33,
   -33,   -15,   -33,   -33,   -33,    -6,    -7,    -8,   -12,   -13,
   -14,    -9,   -11,   -33,   -33,   -21,   -23,   -24,   -29,   -30,
   -31,   -33,   -33,   -33,   -33,   -19,   -33,   -25,   -26,   -32,
   -33,   -10,   -33,   -33,   -22,   -27,   -33,   -17,   -33,   -33,
   -33,   -33,   -28,   -20,   -33,   -18 ]

racc_goto_table = [
    34,    27,    47,    13,    48,    31,    41,    49,     1,    12,
    25,    21,     4,    54,    55,    15,    16,    17,   nil,   nil,
    52,   nil,    59,   nil,   nil,    62,    53,    51,   nil,   nil,
   nil,   nil,   nil,    60,   nil,   nil,   nil,   nil,    64 ]

racc_goto_check = [
    11,     8,    14,    10,    13,     9,     8,    13,     1,     3,
     7,    10,     2,    12,    14,     2,     2,     2,   nil,   nil,
    11,   nil,    13,   nil,   nil,    14,     8,     9,   nil,   nil,
   nil,   nil,   nil,    11,   nil,   nil,   nil,   nil,    11 ]

racc_goto_pointer = [
   nil,     8,    10,     5,   nil,   nil,   nil,    -8,   -18,   -15,
    -1,   -23,   -33,   -33,   -34 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     5,     6,     7,   nil,   nil,   nil,
   nil,   nil,    35,    36,    37 ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 22, :_reduce_1,
  0, 23, :_reduce_none,
  2, 23, :_reduce_none,
  2, 23, :_reduce_none,
  2, 23, :_reduce_none,
  3, 26, :_reduce_6,
  1, 28, :_reduce_7,
  3, 25, :_reduce_8,
  3, 27, :_reduce_9,
  3, 30, :_reduce_10,
  1, 30, :_reduce_11,
  1, 29, :_reduce_12,
  1, 29, :_reduce_13,
  1, 29, :_reduce_14,
  2, 24, :_reduce_15,
  1, 24, :_reduce_16,
  6, 31, :_reduce_17,
  9, 31, :_reduce_18,
  4, 31, :_reduce_19,
  7, 31, :_reduce_20,
  1, 32, :_reduce_21,
  3, 32, :_reduce_22,
  1, 33, :_reduce_23,
  1, 33, :_reduce_24,
  2, 33, :_reduce_25,
  2, 33, :_reduce_26,
  3, 33, :_reduce_27,
  5, 33, :_reduce_28,
  1, 35, :_reduce_29,
  1, 35, :_reduce_30,
  1, 34, :_reduce_31,
  2, 34, :_reduce_32 ]

racc_reduce_n = 33

racc_shift_n = 66

racc_token_table = {
  false => 0,
  :error => 1,
  :EXP => 2,
  :ACTION => 3,
  "=" => 4,
  :TREE => 5,
  :ASSOC => 6,
  :OPERATOR => 7,
  :S_LITERAL => 8,
  "," => 9,
  :NONASSOC => 10,
  :LEFT => 11,
  :RIGHT => 12,
  :IDENTIFIER => 13,
  "." => 14,
  ":" => 15,
  ";" => 16,
  "(" => 17,
  ")" => 18,
  "|" => 19,
  "_" => 20 }

racc_nt_base = 21

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "EXP",
  "ACTION",
  "\"=\"",
  "TREE",
  "ASSOC",
  "OPERATOR",
  "S_LITERAL",
  "\",\"",
  "NONASSOC",
  "LEFT",
  "RIGHT",
  "IDENTIFIER",
  "\".\"",
  "\":\"",
  "\";\"",
  "\"(\"",
  "\")\"",
  "\"|\"",
  "\"_\"",
  "$start",
  "expression",
  "options",
  "expstmts",
  "dassoc",
  "action",
  "nonterm",
  "action_names",
  "assoc",
  "nonterms",
  "expstmt",
  "op_list",
  "op_def",
  "operator",
  "operand" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'higly_racc.y', 6)
  def _reduce_1(val, _values, result)
        tmp = []
    prename = "primaryExpression"
    @opclasses.each do |_,v|
      if v.prename == nil
        v.prename = prename
        v.operators << Op.new(:nonterm, [prename])
        @opclasses[v.name] = v
        prename = v.name
      end
      tmp << v
    end
    @opclasses = tmp
  
    result
  end
.,.,

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

module_eval(<<'.,.,', 'higly_racc.y', 27)
  def _reduce_6(val, _values, result)
     val[2] == :tree ? @tree_flag = true : nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 30)
  def _reduce_7(val, _values, result)
     result = :tree 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 33)
  def _reduce_8(val, _values, result)
     @default_assoc = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 38)
  def _reduce_9(val, _values, result)
        val[2].each do |v|
      @nonterms[v] = 1
    end
  
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 44)
  def _reduce_10(val, _values, result)
     result = val[2] << val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 45)
  def _reduce_11(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 48)
  def _reduce_12(val, _values, result)
     result = :nonassoc
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 49)
  def _reduce_13(val, _values, result)
     result = :left 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 50)
  def _reduce_14(val, _values, result)
     result = :right 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 53)
  def _reduce_15(val, _values, result)
     result = val[1] + val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 54)
  def _reduce_16(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 59)
  def _reduce_17(val, _values, result)
        if @opclasses.key?(val[0])
      @opclasses[val[0]].operators << Op.new(:nonterm, [val[2]])
    else
      @opclasses[val[0]] = OpClass.new(val[0], @default_assoc, [Op.new(:nonterm, [val[2]])])
    end
    child = OpClass.new(val[2], @default_assoc, val[4])
    child.prename = val[0]
    child.parent = val[0]
    @opclasses[val[2]] = child
  
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 71)
  def _reduce_18(val, _values, result)
        if @opclasses.key?(val[0])
      @opclasses[val[0]].operators << Op.new(:nonterm, [val[2]])
    else
      @opclasses[val[0]] = OpClass.new(val[0], val[4], [Op.new(:nonterm, [val[2]])])
    end
    child = OpClass.new(val[2], val[4], val[7])
    child.prename = val[0]
    child.parent = val[0]
    @opclasses[val[2]] = child
  
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 82)
  def _reduce_19(val, _values, result)
     @opclasses[val[0]] = OpClass.new(val[0], @default_assoc, val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 84)
  def _reduce_20(val, _values, result)
     @opclasses[val[0]] = OpClass.new(val[0], val[2], val[5]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 87)
  def _reduce_21(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 88)
  def _reduce_22(val, _values, result)
     result = val[0]<<val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 91)
  def _reduce_23(val, _values, result)
     result = Op.new(:nonterm, val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 92)
  def _reduce_24(val, _values, result)
     result = Op.new(:nonterm, val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 93)
  def _reduce_25(val, _values, result)
     result = Op.new(:lunary, val)
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 94)
  def _reduce_26(val, _values, result)
     result = Op.new(:runary, val)
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 95)
  def _reduce_27(val, _values, result)
     result = Op.new(:binary, val)
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 96)
  def _reduce_28(val, _values, result)
     result = Op.new(:ternary, val)
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 99)
  def _reduce_29(val, _values, result)
     result = 0 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 100)
  def _reduce_30(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 104)
  def _reduce_31(val, _values, result)
     result = token_register(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'higly_racc.y', 105)
  def _reduce_32(val, _values, result)
     result = token_register(val[0]) + " " + val[1] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class HiglyParser


parser = HiglyParser.new
if ARGV[0] then
  File.open(ARGV[0]) do |f|
    parser.parse f
  end

  if ARGV[1] then
    f1 = File.open("#{ARGV[1]}.l", "w")
    f2 = File.open("#{ARGV[1]}.y", "w")
  else
    f1 = File.open("higly.l", "w")
    f2 = File.open("higly.y", "w")
  end

  
  exp = Expression.new(parser.operators, parser.opclasses, parser.tree_flag)

  lex = exp.make_lex()
  yacc = exp.make_yacc_definition()
  yacc += exp.make_yacc_rule()
  yacc += exp.make_yacc_footer()

  f1.puts(lex)
  f2.puts(yacc)
  f1.close
  f2.close
else
  puts "file is nothing. input code."
end
